# Introduction
State notebook purpose here

### Imports
Import libraries and write settings here.

In [1]:
# Data manipulation
import pandas as pd
import numpy as np
from tqdm.autonotebook import tqdm

from IPython import get_ipython
ipython = get_ipython()

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

# Visualizations
#import plotly.plotly as py
#import plotly.graph_objs as go
#from plotly.offline import iplot, init_notebook_mode
#init_notebook_mode(connected=True)

#import cufflinks as cf
#cf.go_offline(connected=True)
#cf.set_config_file(theme='white')


/tmp/ipykernel_92358/2426357776.py:4: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


# Analysis/Modeling
Do work here

# Results
Show graphs and stats here

# Conclusions and Next Steps
Summarize findings here

In [2]:
with open('input.txt','r') as fh:
    lines = fh.readlines()

data = np.array([[int(c) for c in line if c in ['0','1']] for line in lines])

In [3]:
data.shape

(1000, 12)

In [4]:
gamma_bits = data.sum(0)>500

In [5]:
gamma_bits

array([False,  True, False,  True,  True,  True, False,  True, False,
       False,  True,  True])

In [6]:
gamma = (gamma_bits.astype('int')*(2**np.arange(data.shape[-1])[::-1])).sum()

In [7]:
gamma

1491

In [8]:
epsilon = (~gamma) & (2**12-1)

In [9]:
epsilon

2604

In [10]:
print(f'{gamma:012b}\n{epsilon:012b}')

010111010011
101000101100


In [11]:
gamma*epsilon

3882564

In [12]:
def find_remaining_values(data,to_keep=1):
    remaining = data
    for pos in range(data.shape[-1]):
        count = remaining[:,pos].sum()
        print(pos,count,count*2,remaining.shape[0])
        if 2*count > remaining.shape[0]:
            # 1's are more common so keep 0
            print(pos,"keeping 0's")
            mask = remaining[:,pos]==to_keep
        elif 2*count == remaining.shape[0]:
            #equally common so keep 0
            print(pos,"equal, keeping 0's")
            print(remaining)
            mask = remaining[:,pos]==to_keep
        else:
            # 0's are more common so keep 1
            print(pos,"keeping 1's")
            mask = remaining[:,pos]==(1-to_keep)
        if mask.sum() == 0:
            break
        remaining = remaining[mask,:]
    return remaining

In [13]:
def bits_to_decimal(bits):
    return (bits.astype('int')*(2**np.arange(bits.shape[-1])[::-1])).sum()

In [14]:
oxygen_bits = find_remaining_values(data)

0 487 974 1000
0 keeping 1's
1 267 534 513
1 keeping 0's
2 129 258 267
2 keeping 1's
3 71 142 138
3 keeping 0's
4 32 64 71
4 keeping 1's
5 19 38 39
5 keeping 1's
6 8 16 20
6 keeping 1's
7 6 12 12
7 equal, keeping 0's
[[0 1 0 1 0 0 0 0 0 1 1 1]
 [0 1 0 1 0 0 0 0 1 1 1 1]
 [0 1 0 1 0 0 0 0 1 0 0 1]
 [0 1 0 1 0 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 1 0 1 0 1]
 [0 1 0 1 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 1 1 0 1 1]
 [0 1 0 1 0 0 0 0 1 1 1 0]
 [0 1 0 1 0 0 0 1 1 0 0 0]
 [0 1 0 1 0 0 0 1 1 0 0 1]
 [0 1 0 1 0 0 0 1 0 0 1 0]
 [0 1 0 1 0 0 0 0 0 0 1 1]]
8 3 6 6
8 equal, keeping 0's
[[0 1 0 1 0 0 0 1 0 1 0 1]
 [0 1 0 1 0 0 0 1 0 0 0 0]
 [0 1 0 1 0 0 0 1 1 0 1 1]
 [0 1 0 1 0 0 0 1 1 0 0 0]
 [0 1 0 1 0 0 0 1 1 0 0 1]
 [0 1 0 1 0 0 0 1 0 0 1 0]]
9 0 0 3
9 keeping 1's
10 1 2 3
10 keeping 1's
11 1 2 2
11 equal, keeping 0's
[[0 1 0 1 0 0 0 1 1 0 0 0]
 [0 1 0 1 0 0 0 1 1 0 0 1]]


In [15]:
oxygen = bits_to_decimal(oxygen_bits)

In [16]:
oxygen

1305

In [17]:
co2_bits = find_remaining_values(data,to_keep=0)
co2 = bits_to_decimal(co2_bits)

0 487 974 1000
0 keeping 1's
1 261 522 487
1 keeping 0's
2 104 208 226
2 keeping 1's
3 56 112 104
3 keeping 0's
4 27 54 48
4 keeping 0's
5 11 22 21
5 keeping 0's
6 4 8 10
6 keeping 1's
7 2 4 4
7 equal, keeping 0's
[[1 0 1 0 0 0 1 1 0 0 1 1]
 [1 0 1 0 0 0 1 1 0 1 1 1]
 [1 0 1 0 0 0 1 0 0 0 1 0]
 [1 0 1 0 0 0 1 0 1 0 0 1]]
8 1 2 2
8 equal, keeping 0's
[[1 0 1 0 0 0 1 0 0 0 1 0]
 [1 0 1 0 0 0 1 0 1 0 0 1]]
9 0 0 1
9 keeping 1's


In [18]:
oxygen_bits

array([[0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1]])

In [19]:
co2_bits

array([[1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0]])

In [20]:
co2

2594

In [21]:
oxygen*co2

3385170