# Introduction
State notebook purpose here

### Imports
Import libraries and write settings here.

In [1]:
# Data manipulation
import pandas as pd
import numpy as np
from tqdm.autonotebook import tqdm

from IPython import get_ipython
ipython = get_ipython()

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

# Visualizations
#import plotly.plotly as py
#import plotly.graph_objs as go
#from plotly.offline import iplot, init_notebook_mode
#init_notebook_mode(connected=True)

#import cufflinks as cf
#cf.go_offline(connected=True)
#cf.set_config_file(theme='white')


/tmp/ipykernel_121499/2426357776.py:4: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


# Analysis/Modeling
Do work here

# Results
Show graphs and stats here

# Conclusions and Next Steps
Summarize findings here

In [5]:
!head input.txt

8548335644
6576521782
1223677762
1284713113
6125654778
6435726842
5664175556
1445736556
2248473568
6451473526


In [24]:
start = np.fromfile("input.txt",dtype='int8',).reshape((10,11))[:,:-1]-ord('0')

In [67]:
start = np.frombuffer(b"""5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526
""",dtype='int8').reshape((10,11))[:,:-1]-ord('0')

In [7]:
import scipy.ndimage

In [9]:
scipy.ndimage.binary_dilation?

In [11]:
a = np.zeros((5,5))
a[2,2]=1
scipy.ndimage.binary_dilation(a,structure=scipy.ndimage.generate_binary_structure(2,2))

array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [68]:
values = []
flashed = []
now = start.copy()
for k in range(99):
    now = now + 1
    flash = np.zeros(now.shape,dtype=bool)
    while np.any(now[~flash]>9):
        flashing_now = now>9
#        print(f"flashing this round: {(now>9).sum()}")
        now[flashing_now]=0
        flash = flash | flashing_now
        affected = scipy.ndimage.binary_dilation(flashing_now,structure=scipy.ndimage.generate_binary_structure(2,2)).astype('bool')
        now[affected] = now[affected]+1
        now[flashing_now] = 0
    now[flash] = 0
    values.append(now)
    flashed.append(flash)
values = np.array(values)
flashed=np.array(flashed)

In [69]:
values.shape

(99, 10, 10)

In [70]:
flashed.sum()

1688

In [72]:
values[0]

array([[6, 5, 9, 4, 2, 5, 4, 3, 3, 4],
       [3, 8, 5, 6, 9, 6, 5, 8, 2, 2],
       [6, 3, 7, 5, 6, 6, 7, 2, 8, 4],
       [7, 2, 5, 2, 4, 4, 7, 2, 5, 7],
       [7, 4, 6, 8, 4, 9, 6, 5, 8, 9],
       [5, 2, 7, 8, 6, 3, 5, 7, 5, 6],
       [3, 2, 8, 7, 9, 5, 2, 8, 3, 2],
       [7, 9, 9, 3, 9, 9, 2, 2, 4, 5],
       [5, 9, 5, 7, 9, 5, 9, 6, 6, 5],
       [6, 3, 9, 4, 8, 6, 2, 6, 3, 7]], dtype=int8)

In [73]:
values[1]

array([[8, 8, 0, 6, 4, 7, 6, 5, 5, 5],
       [5, 0, 8, 8, 0, 8, 7, 0, 5, 4],
       [8, 5, 9, 7, 8, 8, 9, 5, 0, 8],
       [8, 4, 8, 5, 7, 6, 9, 6, 0, 0],
       [8, 7, 0, 0, 9, 0, 8, 8, 0, 0],
       [6, 6, 0, 0, 0, 6, 7, 9, 8, 9],
       [5, 6, 0, 0, 0, 8, 4, 9, 4, 3],
       [9, 0, 0, 7, 0, 0, 4, 4, 5, 6],
       [7, 0, 8, 0, 0, 8, 0, 8, 7, 6],
       [8, 5, 0, 8, 0, 9, 4, 8, 4, 8]], dtype=int8)

In [75]:
flashed[1].astype('int8')

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)

In [17]:
flashed.sum()

1000

In [19]:
flashed.astype('int32').sum()

1000