# Introduction
State notebook purpose here

### Imports
Import libraries and write settings here.

In [1]:
# Data manipulation
import pandas as pd
import numpy as np
from tqdm.autonotebook import tqdm

from IPython import get_ipython
ipython = get_ipython()

# Options for pandas
pd.options.display.max_columns = 50
pd.options.display.max_rows = 30

# autoreload extension
if 'autoreload' not in ipython.extension_manager.loaded:
    %load_ext autoreload

%autoreload 2

# Visualizations
#import plotly.plotly as py
#import plotly.graph_objs as go
#from plotly.offline import iplot, init_notebook_mode
#init_notebook_mode(connected=True)

#import cufflinks as cf
#cf.go_offline(connected=True)
#cf.set_config_file(theme='white')


/tmp/ipykernel_93041/2426357776.py:4: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


# Analysis/Modeling
Do work here

# Results
Show graphs and stats here

# Conclusions and Next Steps
Summarize findings here

In [6]:
!head input.txt

73,42,95,35,13,40,99,92,33,30,83,1,36,93,59,90,55,25,77,44,37,62,41,47,80,23,51,61,21,20,76,8,71,34,58,5,52,22,39,57,17,2,26,0,10,72,19,3,64,65,82,46,31,63,91,24,18,12,9,79,50,98,69,4,78,54,43,68,87,7,67,48,28,89,94,53,85,81,49,88,6,96,29,56,97,66,38,16,32,70,74,27,84,86,45,75,60,15,14,11

91  5 64 81 34
15 99 31 63 65
45 39 54 93 83
51 14 23 86 32
19 22 16 13  3

20 83 38 85 70
69 12 14 26 84


In [10]:
draws = np.loadtxt('input.txt',max_rows=1,delimiter=',')
boards = np.genfromtxt('input.txt',skip_header=1,)

In [11]:
boards.shape

(500, 5)

In [4]:
draws.shape

(100,)

In [5]:
draws

array([73., 42., 95., 35., 13., 40., 99., 92., 33., 30., 83.,  1., 36.,
       93., 59., 90., 55., 25., 77., 44., 37., 62., 41., 47., 80., 23.,
       51., 61., 21., 20., 76.,  8., 71., 34., 58.,  5., 52., 22., 39.,
       57., 17.,  2., 26.,  0., 10., 72., 19.,  3., 64., 65., 82., 46.,
       31., 63., 91., 24., 18., 12.,  9., 79., 50., 98., 69.,  4., 78.,
       54., 43., 68., 87.,  7., 67., 48., 28., 89., 94., 53., 85., 81.,
       49., 88.,  6., 96., 29., 56., 97., 66., 38., 16., 32., 70., 74.,
       27., 84., 86., 45., 75., 60., 15., 14., 11.])

In [12]:
boards = boards.reshape((-1,5,5))

In [13]:
boards[0]

array([[91.,  5., 64., 81., 34.],
       [15., 99., 31., 63., 65.],
       [45., 39., 54., 93., 83.],
       [51., 14., 23., 86., 32.],
       [19., 22., 16., 13.,  3.]])

In [29]:
hits = np.zeros(boards.shape,dtype=np.bool_)
for i_draw,draw in enumerate(draws):
    hits = hits | (boards==draw)
    row_wins = np.any(hits.sum(1)==boards.shape[1],axis=1)
    col_wins = np.any(hits.sum(2)==boards.shape[2],axis=1)
    winning_board = np.flatnonzero(row_wins | col_wins)
    if len(winning_board):
        winner = boards[winning_board[0]]
        board_hits = hits[winning_board[0]]
        unmarked = winner[~board_hits]
        result = draw*(unmarked.sum())
        print(draws[:i_draw+1],winner,result)
        break
        

[73. 42. 95. 35. 13. 40. 99. 92. 33. 30. 83.  1. 36. 93. 59. 90. 55. 25.
 77. 44. 37. 62. 41. 47. 80. 23. 51. 61. 21. 20. 76.  8. 71.] [[64. 65.  6. 86. 53.]
 [10. 56.  2. 88. 73.]
 [11. 62. 37. 84.  1.]
 [71. 42. 76. 51. 77.]
 [41. 83. 19. 14.  4.]] 39902.0


In [32]:
hits = np.zeros(boards.shape,dtype=np.bool_)
for i_draw,draw in enumerate(draws):
    hits = hits | (boards==draw)
    row_wins = np.any(hits.sum(1)==boards.shape[1],axis=1)
    col_wins = np.any(hits.sum(2)==boards.shape[2],axis=1)
    winning_boards = np.flatnonzero(row_wins | col_wins)
    if len(winning_boards)==boards.shape[0]:
        last_winner_index = list(set(winning_boards)-set(last_winners))[0]
        print(last_winner_index)
        winner = boards[last_winner_index]
        board_hits = hits[last_winner_index]
        unmarked = winner[~board_hits]
        result = draw*(unmarked.sum())
        print(draws[:i_draw+1],winner,result)
        break
    last_winners = winning_boards
        

45
[73. 42. 95. 35. 13. 40. 99. 92. 33. 30. 83.  1. 36. 93. 59. 90. 55. 25.
 77. 44. 37. 62. 41. 47. 80. 23. 51. 61. 21. 20. 76.  8. 71. 34. 58.  5.
 52. 22. 39. 57. 17.  2. 26.  0. 10. 72. 19.  3. 64. 65. 82. 46. 31. 63.
 91. 24. 18. 12.  9. 79. 50. 98. 69.  4. 78. 54. 43. 68. 87.  7. 67. 48.
 28. 89. 94. 53. 85. 81. 49. 88.  6. 96. 29. 56.] [[78. 56. 29. 50. 32.]
 [79. 92. 38. 49. 45.]
 [70. 80. 76. 86. 64.]
 [53. 22. 20. 66. 60.]
 [77. 25. 84. 93. 88.]] 26936.0


In [26]:
hits[winning_board[0]]

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False]])

In [17]:
winning_board

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
hits | 

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       ...,

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, Fals

In [21]:
boards==draw

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       ...,

       [[ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, Fals